#!/bin/bash

set -e

sudo apt-get install python-dev clang libcurl4-openssl-dev

# install gtest
sudo apt-get install libgtest-dev

sudo apt-get install cmake
cd /usr/src/gtest
sudo cmake CMakeLists.txt
sudo make
 
# copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
sudo cp *.a /usr/local/lib
