PWD             := $(shell pwd)
TMPDIR          := ${PWD}/../../tmp
$(shell mkdir -p ${TMPDIR}>/dev/null)
FILENAME        := ${TMPDIR}/makeenv
IGNORE          := $(shell bash -c "source ../../env.sh; env | sed 's/=/:=/' | sed 's/^/export /' > ${FILENAME}")
include ${FILENAME}

CFLAGS          := $(CFLAGS) -Wall -O2 -fPIC
DEPDIR           = .d
$(shell mkdir -p ${DEPDIR}>/dev/null)
DEPFLAGS         = -MT $@ -MMD -MP -MF ${DEPDIR}/$*.Td
POSTCOMPILE      = @mv -f ${DEPDIR}/$*.Td ${DEPDIR}/$*.d
